---
- name: Install OpenSSH server package
  ansible.builtin.apt:
    pkg:
      - openssh-server
    update_cache: true
  notify: Reboot

- name: Setting sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config.d/99-custom.conf
    line: "{{ item }}"
    create: true
    mode: "0644"
  with_items:
    - PermitRootLogin no
    - PubkeyAuthentication yes
    - PasswordAuthentication no
    - PermitEmptyPasswords no
    - ChallengeResponseAuthentication no
  notify: Reload ssh

- name: Setting public key
  ansible.posix.authorized_key:
    user: seapolis
    state: present
    key: "{{ lookup('file', '../files/seapolis.pub') }}"
